import type { Metadata } from "next";
import { Instrument_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import RegisterSW from "@/components/RegisterSW";
import { AuthProvider } from "@/hooks/useAuth";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Yap",
  description: "Generated by create Bob",
  manifest: "/manifest.json",
  icons: {
    icon: '/yap-mascot.svg',
    apple: '/yap-mascot.png',
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Yap",
  },
};

export const viewport = {
  themeColor: "#000000",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${ibmPlexMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <RegisterSW />
        <AuthProvider>
        {children}
        </AuthProvider>
        </body>
    </html>
  );
}