export { default as Comfort } from  '@/components/Decks/Comfort'
export { default as DeepTalk } from '@/components/Decks/DeepTalk'
export { default as Couples } from '@/components/Decks/Couples'
export { default as Footer } from '@/components/Decks/Footer'
export { default as SwipeCard } from '@/components/Decks/SwipeCard'
export { default as Intimacy } from '@/components/Decks/Intimacy'
export { default as ShowAnswer } from '@/components/Decks/ShotAnswer'